### ISSUE TITLE
[Question] getting the latest version with bug fixes

### ISSUE THREAD

**Issue by ethren** [OpenFOAM/OpenFOAM-6#2]
Hello, 
I am tired of searching the internet to get an answer to my question, so I decided to ask it here!
In Ubuntu:
**Without** installing OpenFOAM-dev. How can I get OpenFOAM with the latest bug fixes? do I have to wait till OpenFOAM 7 to be released?
or do you provide regularly pre-compiled versions via ubuntu repositories? if yes when?
Please answer me.

**Comment by OpenFOAM** [comment]
https://openfoam.org/contact/
https://bugs.openfoam.org/rules.php
