### ISSUE TITLE
Compiling Problems

### ISSUE THREAD

**Issue by Volker-Weissmann** [OpenFOAM/OpenFOAM-6#3]
I read this https://openfoam.org/download/source/ explanation on how to compile OpenFoam from source. I tried running this script:

    #!/bin/bash
    apt-get install build-essential flex bison git-core cmake zlib1g-dev libboost-system-dev libboost-thread-dev libopenmpi-dev openmpi-bin gnuplot libreadline-dev libncurses-dev libxt-dev
    apt-get install qt4-dev-tools libqt4-dev libqt4-opengl-dev freeglut3-dev libqtwebkit-dev curl
    
    rm -r OpenFOAM-6
    rm -r ThirdParty-6
    rm -r /opt/OpenFOAM-6
    rm -r /opt/ThirdParty-6
    git clone git://github.com/OpenFOAM/OpenFOAM-6.git
    git clone git://github.com/OpenFOAM/ThirdParty-6.git
    cp -r OpenFOAM-6 /opt/
    cp -r ThirdParty-6 /opt/
    source /opt/OpenFOAM-6/etc/bashrc
    export WM_COMPILE_OPTION=Debug
    /opt/ThirdParty-6/Allwmake -j
    /opt/ThirdParty-6/makeParaView
    wmRefresh
    /opt/OpenFOAM-6/src/Allwmake -j
But this script failed with the following output:

    ... a lot of output without erros ...
    -- Installing: /opt/ThirdParty-6/platforms/linux64Gcc/ParaView-5.4.0/share/doc/paraview-5.4/paraview.qch
        ---
        Installation complete for paraview-5.4.0
        Now update the environment by running:
            wmRefresh
        ---
    
    Done
    /opt/OpenFOAM-6/etc/config.sh/aliases: line 85: wmUnset: command not found
    Compiling enabled on 4 cores
    Allwmake src
    version changed from previous build
    removing .o files corresponding to OpenFOAM/global/global.o ...
    Allwmake src/Pstream
    wmake dummy
    wmakeLnIncludeAll: running wmakeLnInclude on dependent libraries:
        wmakeLnInclude: linking include files to /opt/OpenFOAM-6/src/OpenFOAM/lnInclude
        wmakeLnInclude: linking include files to /opt/OpenFOAM-6/src/OSspecific/POSIX/lnInclude
    wmakeLnInclude: linking include files to ./lnInclude
    Making dependency list for source file UOPwrite.C
    Making dependency list for source file UIPread.C
    Making dependency list for source file UPstream.C
    make: /opt/OpenFOAM-6/wmake/platforms/linux64Gcc/wmkdep: Command not found
    make: /opt/OpenFOAM-6/wmake/platforms/linux64Gcc/wmkdep: Command not found
    make: /opt/OpenFOAM-6/wmake/platforms/linux64Gcc/wmkdep: Command not found
    make: *** No rule to make target '/opt/OpenFOAM-6/platforms/linux64GccDPInt32Opt/src/Pstream/dummy/UPstream.C.dep', needed by '/opt/OpenFOAM-6/platforms/linux64GccDPInt32Opt/src/Pstream/dummy/UPstream.o'.  Stop.
I would be thankful if anyone could explain to me why the compilation failes and how to fix it.

Additional Info:
OS: Linux (Ubuntu 18.04)

**Comment by OpenFOAM** [comment]
https://bugs.openfoam.org/rules.php

**Comment by QwertyJack** [comment]
`wmUnset` is an alias not a function nor command, and alias is not expanded in a non-interactive shell, as goes in bash manpage:

> Aliases are not expanded when the shell is not interactive, unless the expand_aliases shell option is set using shopt (see the description of shopt under SHELL BUILTIN COMMANDS below).

So the solution is **either**:

- put a `shopt -s expand_aliases` at the very beginning of your script, **OR**
- find out what the alias really is and call the function or the command behind it

See also: https://unix.stackexchange.com/questions/1496/why-doesnt-my-bash-script-recognize-aliases

**Comment by OpenFOAM** [comment]
https://bugs.openfoam.org/rules.php

**Comment by QwertyJack** [comment]
@Volker-Weissmann
