### ISSUE TITLE
Missing drag models in makeThermoParcelForces

### ISSUE THREAD

**Issue by lahwaacz** [OpenFOAM/OpenFOAM-6#5]
Why does the `makeThermoParcelForces` macro create only `SphereDragForce` and `NonSphereDragForce`, while `makeParcelForces` creates also `WenYuDragForce`, `ErgunWenYuDragForce`, and `PlessisMasliyahDragForce`?

https://github.com/OpenFOAM/OpenFOAM-6/blob/master/src/lagrangian/intermediate/parcels/include/makeThermoParcelForces.H
https://github.com/OpenFOAM/OpenFOAM-6/blob/master/src/lagrangian/intermediate/parcels/include/makeParcelForces.H

**Comment by OpenFOAM** [comment]
https://bugs.openfoam.org/rules.php

**Comment by lahwaacz** [comment]
The linked website does not have a section for questions either...
