### ISSUE TITLE
foamCloneCase script 

### ISSUE THREAD

**Issue by Rvadrabade** [OpenFOAM/OpenFOAM-6#6]
currently foamCloneCase script is not accepting target directory name on ubuntu terminal with double tab.
e.g. foamCloneCase cavity <TAB><TAB>.
If it does foamCloneCase cavity <Tab><TAB>{to automatically select "cavity" word }2.

**Comment by OpenFOAM** [comment]
https://bugs.openfoam.org/rules.php
