### ISSUE TITLE
The capability of component residualControl should be added to OpenFOAM

### ISSUE THREAD

**Issue by D-Benjamin** [OpenFOAM/OpenFOAM-6#7]
Hi All,
I‘m doing a 2D axis symmetry case which is need to use wedge mesh. The circumferential velocity(z direction) which I don't care about is calculated and it is hard to be convergent. Therefore, I wanna set different "residualControl" on velocity field "U", for example,
```
    residualControl
    {
        p               1e-3;
        //U               1e-5;
        Ux              1e-5;
        Uy              1e-5;
        Uz              1e-2;
        "(k|epsilon)"   1e-3;
    }
```
However, I found there was no the capability of component "residualControl", it seemed like that there is no "residualControl" set  on "U" when I changed the "U" to the "Ux, Uy, Uz", though it didn't show any error or warning when I did this change.
Any reply will be great appreciated! Thanks!

**Comment by D-Benjamin** [comment]
By the way, the OpenFOAM version I'm using is OpenFOAM-6

**Comment by OpenFOAM** [comment]
https://bugs.openfoam.org/rules.php
