### ISSUE TITLE
Documentation missing wget

### ISSUE THREAD

**Issue by vsoch** [OpenFOAM/OpenFOAM-6#9]
hey Openfoam! I'm not sure where your bug tracker is, but this is a tiny issue with the documentation [here](https://openfoamwiki.net/index.php/Installation/Linux/OpenFOAM-1.6-ext/Ubuntu#Ubuntu_16.04) that I hope helps someone in the future!  We were working on building a Docker container [details here](https://ask.cyberinfrastructure.org/t/how-do-i-create-a-docker-container-for-openfoam-1-6-ext/989) using an Ubuntu 16.04 base and a lot of issues came down to missing wget (so the ThirdParty libraries weren't built) and then ld issued a bunch of missing library commands. So - if we just add it to the list, many future users will likely appreciate :)

**Comment by OpenFOAM** [comment]
https://bugs.openfoam.org/rules.php

**Comment by vsoch** [comment]
I don't really want to sign up for another account, sorry. Just wanted to let you know. Have a nice day.
